version: "3.7"
services:
  web:
    build: .
    environment:
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
    volumes:
      - .:/app
    command: npm run ${ENV}
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
