version: "3.7"
services:
  web:
    build: .
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
    command: npm run dev
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
