version: "3.7"
services:
  web:
    build: .
    volumes:
      - .:/app
    command: sh -c "npm i && npm run production"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
